services:
  planetarium:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: planetarium
      POSTGRES_PASSWORD: planetarium
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "planetarium" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
