# Generated by Django 5.1.4 on 2024-12-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'show_session')},
        ),
    ]
